### PR TITLE
Delete recipe/conda_build_config.yaml to load package on main channel

### LINKED ISSUE #15: Is there a reason this only publishes to the `dlltracer_dev` label?
### Comment:

It took me a while to figure out why I couldn't install it! 😅 

https://github.com/conda-forge/dlltracer-feedstock/blob/ed9a8472e37b48246e58e41e267d6feff2938749/recipe/conda_build_config.yaml#L1-L2

### PR DESCRIPTION
**Pull request by traversaro**
Fix https://github.com/conda-forge/dlltracer-feedstock/issues/15 .

Checklist
* [x] Used a [personal fork of the feedstock to propose changes](https://conda-forge.org/docs/maintainer/updating_pkgs.html#forking-and-pull-requests)
* [x] Bumped the build number (if the version is unchanged)
* [ ] Reset the build number to `0` (if the version changed)
* [x] [Re-rendered]( https://conda-forge.org/docs/maintainer/updating_pkgs.html#rerendering-feedstocks ) with the latest `conda-smithy` (Use the phrase <code>@<space/>conda-forge-admin, please rerender</code> in a comment in this PR for automated rerendering)
* [x] Ensured the license file is being packaged.

### CODE REVIEW

**Comment by traversaro** [comment]
@conda-forge-admin, please rerender

**Comment by xhochy** [comment]
@conda-forge-admin please rerender

**Comment by xhochy** [comment]
Tests fail:

```
import: 'dlltracer'
ERROR: Exception:
Traceback (most recent call last):
  File "D:\bld\dlltracer_1725462065985\_test_env\lib\site-packages\pip\_internal\cli\base_command.py", line 105, in _run_wrapper
    status = _inner_run()
  File "D:\bld\dlltracer_1725462065985\_test_env\lib\site-packages\pip\_internal\cli\base_command.py", line 96, in _inner_run
    return self.run(options, args)
  File "D:\bld\dlltracer_1725462065985\_test_env\lib\site-packages\pip\_internal\commands\check.py", line 29, in run
    unsupported = list(
  File "D:\bld\dlltracer_1725462065985\_test_env\lib\site-packages\pip\_internal\operations\check.py", line 139, in check_unsupported
    wheel_tags: FrozenSet[Tag] = reduce(
  File "D:\bld\dlltracer_1725462065985\_test_env\lib\site-packages\pip\_vendor\packaging\tags.py", line 104, in parse_tag
    interpreters, abis, platforms = tag.split("-")
ValueError: not enough values to unpack (expected 3, got 2)

```

**Review by dhirschfeld — APPROVED** [review]
:shipit:

**Pull request merged**
